name: sistema-asa CI

on:
  push:
    branches:
      - teste

env:
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

jobs:
  build-backend:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Install dependencies
        run: |
          cd Back-end
          dotnet restore

      - name: Install dotnet-ef tool
        run: |
          dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply database migrations
        run: |
          cd Back-end
          dotnet ef database update
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}

      - name: Build project
        run: |
          cd Back-end
          dotnet build

      - name: Run backend application
        run: |
          cd Back-end
          dotnet run
    
  build-frontend:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run frontend application
        run: dotnet run --project Front-end/Front-end.csproj

  run-tests:
    runs-on: windows-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Install dependencies
        run: dotnet restore

      - name: Wait for backend and frontend
        run: |
          echo "Wait for 15 seconds."
          sleep 15 

      - name: Run unit tests
        run: dotnet test ./testeDeUnidade/testeDeUnidade.csproj

      - name: Run system tests
        run: dotnet test ./testeDeSistema/testeDeSistema.csproj